### ISSUE TITLE
Pull and build instructions

### ISSUE THREAD

**Issue by DusteDdk** [lets-all-be-stupid-forever/circuit-artist#3]
Greetings, I've tried to build the game, and I'm not super advanced, but also not a total noob.

First issue: The standard way of checking out does not work, the project uses submodules, and I don't know how people are supposed to guess that, I am not sure if the the command I found by searching online is the right one, but I think it'd be helpful to include whatever command is needed if a simple "git clone URL" is not enough :)

Is it this one ?

`git clone --recurse-submodules -j8  https://github.com/lets-all-be-stupid-forever/circuit-artist.git`

Next up, there is no build directory, and no instruction on how to actually start the build.

Again, I don't know if these are correct, so please adjust if they're not :)

```
make build && cd build
cmake ..

```
This does generate makefiles, but the build fails:

`make -j 8 `

[Truncated most build output, full build log here](https://github.com/user-attachments/files/17024669/circuit-full-log.txt)

```
<command-line>: error: macro names must be identifiers
<command-line>: error: macro names must be identifiers
<command-line>: error: macro names must be identifiers
<command-line>: error: macro names must be identifiers
<command-line>: error: macro names must be identifiers
<command-line>: error: macro names must be identifiers
make[2]: *** [CMakeFiles/ca.dir/build.make:76: CMakeFiles/ca.dir/src/main.c.o] Error 1
make[2]: *** Waiting for unfinished jobs....
<command-line>: error: macro names must be identifiers
<command-line>: error: macro names must be identifiers
make[2]: *** [CMakeFiles/ca.dir/build.make:118: CMakeFiles/ca.dir/src/filedialog.c.o] Error 1
make[2]: *** [CMakeFiles/ca.dir/build.make:132: CMakeFiles/ca.dir/src/colors.c.o] Error 1
make[2]: *** [CMakeFiles/ca.dir/build.make:160: CMakeFiles/ca.dir/src/msg.c.o] Error 1
make[2]: *** [CMakeFiles/ca.dir/build.make:90: CMakeFiles/ca.dir/src/brush.c.o] Error 1
make[2]: *** [CMakeFiles/ca.dir/build.make:146: CMakeFiles/ca.dir/src/tiling.c.o] Error 1
make[2]: *** [CMakeFiles/ca.dir/build.make:174: CMakeFiles/ca.dir/src/minimap.c.o] Error 1
make[2]: *** [CMakeFiles/ca.dir/build.make:104: CMakeFiles/ca.dir/src/paint.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:184: CMakeFiles/ca.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
dusted@detail:~/code/circuit-artist/build$ make
[  2%] Built target nfd
[ 54%] Built target glfw
[ 64%] Built target raylib
[ 65%] Building C object CMakeFiles/ca.dir/src/main.c.o
<command-line>: error: macro names must be identifiers
make[2]: *** [CMakeFiles/ca.dir/build.make:76: CMakeFiles/ca.dir/src/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:184: CMakeFiles/ca.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
dusted@detail:~/code/circuit-artist/build$ make
[  2%] Built target nfd
[ 54%] Built target glfw
[ 64%] Built target raylib
[ 65%] Building C object CMakeFiles/ca.dir/src/main.c.o
<command-line>: error: macro names must be identifiers
make[2]: *** [CMakeFiles/ca.dir/build.make:76: CMakeFiles/ca.dir/src/main.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:184: CMakeFiles/ca.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
dusted@detail:~/code/circuit-artist/build$
```

I'm kind of lost here, I've not looked into the cmake files, but from stackoverflow I'm seeing an answer to a similar looking issue: 

"Like said, you probably have a -D flag with no name.
However, if you are using cmake, this can happen if you mistakingly add an option to compile definitions instead of compile options."

So that might be worth looking at. 

Cool looking project, love the aesthetic and theme, so I can't wait to try it out! :) :+1:  :100:

**Comment by lets-all-be-stupid-forever** [comment]
Hi. You're on linux right?

The command that I do after cloning is:

```
git submodule init
git submodule update
```
Maybe there's a better way to clone and update the submodules as you've found.

Yes there was a bad -D argument early on, but it was fixed, you can try rebasing the latest version of master.
That should fix the -D thing.

Then you'll have to create a symbolic link to luajit: First go to LuaJIT/ and do a `make`. Then, you have to create a symbolic link from the `build/` folder to the `Luajit/src/libluajit.so` file: `cd build && ln -s ../LuaJIT/src/libluajit.so libluajit-5.1.so.2`, something like that.

That should be enough to compile the executable. Then you can launch via `LD_LIBRARY_PATH=$PWD ./ca`. 

I develop mainly in windows, I'm still trying to make the build process easier/cleaner for mac and linux.

**Comment by lets-all-be-stupid-forever** [comment]
That's weird, I just compiled it here, here are the exact commands I ran: (I'm on a Ubuntu VM)

```
  git clone https://github.com/lets-all-be-stupid-forever/circuit-artist.git\
  git submodule init
  cd circuit-artist/
  git submodule init
  git submodule update
  mkdir build
  cd build/
  cmake ..
  make -C ../LuaJIT/
  make -j
  ln -s ../LuaJIT/src/libluajit.so libluajit-5.1.so.2 
  LD_LIBRARY_PATH=$PWD ./ca
```

**Comment by DusteDdk** [comment]
Slightly different commands than I used. I found the cause of the macro stuff and fixed it in cmakelists, I've created a pull request which adds this small fix and updates the readme with exact instructions for compiling on Linux, I got it working now and am having some fun! Thanks for making this! :)

**Comment by lets-all-be-stupid-forever** [comment]
Indeed, I wasnt able to reproduce the cmake issue in my VM for some reason. Thanks for the PR! 
Hope you like the game!

**Comment by lets-all-be-stupid-forever** [comment]
#5 merged
